GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/get/5555

###

POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Leave a Light On",
    "artist": "Tom Walker",
    "year": "2022",
    "id": 102663
}

###

PUT http://localhost:3000/songs/5555
Content-Type: application/json

{
    "title": "Insert title here",
    "artist": "Insert Name here",
    "year": "Insert date here",
    "id": 5555
}

###

DELETE http://localhost:3000/songs/3290637