GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/8219617

###

POST http://localhost:3000/songs

###

PUT http://localhost:3000/songs/7379947

###

DELETE http://localhost:3000/songs/7379947